/* ======================================================================
   PRODUTOS.JS — Catálogo do cardápio
   ----------------------------------------------------------------------
   Edite este arquivo para adicionar, remover ou alterar produtos.
   Não é necessário mexer em nenhum outro arquivo do site.
   ====================================================================== */

/* ----------------------------------------------------------------------
   1) CATEGORIAS
   Defina aqui a ordem em que as categorias aparecem no menu e nas abas
   de filtro. O texto precisa ser IGUAL ao campo "categoria" usado nos
   produtos lá embaixo.
---------------------------------------------------------------------- */
const CATEGORIAS = [
  "Burgers",
  "Combos",
  "Porções",
  "Bebidas",
  "Sobremesas",
];

/* ----------------------------------------------------------------------
   2) ADICIONAIS
   Lista global de adicionais que aparece na tela de qualquer produto que
   tenha "adicionais: true". Para um produto não mostrar adicionais
   (ex.: bebidas), basta colocar "adicionais: false" nesse produto.
---------------------------------------------------------------------- */
const ADICIONAIS = [
  { nome: "Bacon", preco: 2.00 },
  { nome: "Ovo", preco: 1.50 },
  { nome: "Salada (alface e tomate)", preco: 1.50 },
  { nome: "Picles", preco: 1.00 },
  { nome: "Cebola roxa", preco: 1.00 },
  { nome: "Cebola caramelizada", preco: 2.00 },
  { nome: "Catupiry", preco: 2.50 },
  { nome: "Cheddar cremoso", preco: 2.50 },
  { nome: "Geleia de pimenta", preco: 1.50 },
  { nome: "Gorgonzola", preco: 2.50 },
  { nome: "Queijo prato", preco: 2.00 },
  { nome: "Muçarela", preco: 2.00 },
  { nome: "Queijo gouda", preco: 2.50 },
  { nome: "Burger de fraldinha", preco: 6.00 },
  { nome: "Burger de costela", preco: 6.00 },
  { nome: "Burger de picanha", preco: 8.00 },
  { nome: "Burger de frango", preco: 5.00 },
  { nome: "Carne seca desfiada", preco: 4.00 },
  { nome: "Costela desfiada", preco: 4.00 },
  { nome: "Presunto", preco: 1.50 },
  { nome: "Trocar por burger 200g", preco: 3.00 }
];

/* ----------------------------------------------------------------------
   3) PRODUTOS
   Cada produto aceita os seguintes campos:

   id           -> número único (não repetir)
   categoria    -> precisa bater com um item da lista CATEGORIAS acima
   nome         -> nome exibido no card e no modal
   desc         -> frase curta exibida embaixo do nome (card e modal)
   ingredientes -> texto exibido no modal, dentro de "Ingredientes"
   preco        -> preço base, em número (use ponto, não vírgula)
   imagem       -> URL da foto do produto
   adicionais   -> true/false — mostra ou esconde o bloco de adicionais
   observacoes  -> true/false — mostra ou esconde o campo de observações
   destaque     -> true/false — opcional, mostra selo "Mais pedido" no card
---------------------------------------------------------------------- */
const PRODUTOS = [

  /* ---------------- BURGERS ---------------- */
  {
    id: 1,
    categoria: "Burgers",
    nome: "Australiano",
    desc: "Pão australiano, molho verde, burger de costela 200g, queijo prato, cebola roxa, rúcula e bacon.",
    preco: 22.90,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/e84b88fecd4ee3d971bafd927bc42cec.png",
    adicionais: true,
    observacoes: true,
    destaque: true,
  },
  {
    id: 2,
    categoria: "Burgers",
    nome: "Baconese",
    desc: "Pão com Gergelim, molho baconese, burger de fraldinha 200g, queijo muçarela, cebola roxa, alface, tomate e bacon.",
    preco: 22.90,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/0d228b511a3e1eab8a1613edf4146e7d.png",
    adicionais: true,
    observacoes: true,
  },
  {
    id: 3,
    categoria: "Burgers",
    nome: "Baconpiry",
    desc: "Pão Brioche, molho gourmet, burger de fraldinha 200g, queijo muçarela, catupiry e bacon.",
    preco: 22.90,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/c9224adcc668cbdfe033992b206b598f.png",
    adicionais: true,
    observacoes: true,
  },
  {
    id: 4,
    categoria: "Burgers",
    nome: "Cheddar Burger",
    desc: "Pão com gergelim, molho barbecue, burger de fraldinha 200g, cheddar cremoso, bacon, picles e cebola caramelizada.",
    preco: 23.50,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/8b1f73d5c512406e60fe7e8c758428d3.png",
    adicionais: true,
    observacoes: true,
  },
  {
    id: 5,
    categoria: "Burgers",
    nome: "Chicken Burger",
    desc: "Pão com gergelim, molho gourmet, molho 4 queijos, burger de frango 200g e bacon.",
    preco: 22.90,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/5a839221e9d4716606594a67f2e9e2c2.png",
    adicionais: true,
    observacoes: true,
  },  {
    id: 6,
    categoria: "Burgers",
    nome: "Cowboy Burger",
    desc: "Pão Brioche, maionese gourmet, burger de fraldinha 100g, catupiry, alho frito, carne seca desfiada e couve crispy.",
    preco: 23.90,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/297bfdc2c8ff454e184f92f37bd926d5.png",
    adicionais: true,
    observacoes: true,
  },  {
    id: 7,
    categoria: "Burgers",
    nome: "Double Cheddar",
    desc: "Pão com gergelim, molho barbecue, 2 burgers de fraldinha 200g, cheddar cremoso, bacon, picles e cebola caramelizada.",
    preco: 27.90,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/98f33e0d3de77ba7cfd3f9d19676b451.png",
    adicionais: true,
    observacoes: true,
  },  {
    id: 8,
    categoria: "Burgers",
    nome: "Double Costelão",
    desc: "Pão Francês, molho verde, 2 burgers costela 200g,2 ovos, queijo prato, bacon, cebola roxa, alface e tomate",
    preco: 27.90,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/cf10247c96d58e4a0461ebf9670d72d6.png",
    adicionais: true,
    observacoes: true,
  },  {
    id: 9,
    categoria: "Burgers",
    nome: "Double Picanha",
    desc: "Pão australiano, molho da casa, 2 burgers de picanha 200g, catupiry em dobro, alho frito, bacon em dobro e rúcula.",
    preco: 30.90,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/2fb2299175ea8f0d0f784b59d145ce68.png",
    adicionais: true,
    observacoes: true,
  },  {
    id: 10,
    categoria: "Burgers",
    nome: "Extra Cheese Bacon",
    desc: "Pão brioche, molho gourmet, 2 burgers de 100g cada, queijo prato e bacon.",
    preco: 20.90,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/d570f2bcb7c397ed1039c1fc16a16b5d.png",
    adicionais: true,
    observacoes: true,
  },  {
    id: 11,
    categoria: "Burgers",
    nome: "La Brasa",
    desc: "Pão brioche, molho barbecue, burger de fraldinha 200g e queijo prato.",
    preco: 19.90,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/e37e7951384155cdc2afe320ed3d8afe.png",
    adicionais: true,
    observacoes: true,
  },  {
    id: 12,
    categoria: "Burgers",
    nome: "La Brasa Master",
    desc: "2 pães francês, molho gourmet ,5 burgers de fraldinha 200g, fatias de queijo muçarela, 10 tiras de bacon, 5 ovos, picles, alface e tomate",
    preco: 79.99,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/b46bde94d4ee10cfca70a3c69c93234d.png",
    adicionais: true,
    observacoes: true,
    destaque: true,
  },  {
    id: 13,
    categoria: "Burgers",
    nome: "La brasa Picante",
    desc: "Pão brioche, molho gourmet, burger de fraldinha 200g, alface, queijo gouda e geleia de pimenta.",
    preco: 21.90,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/21ef95b1bd4d3d05903b9db0b6c6165e.png",
    adicionais: true,
    observacoes: true,
  },  {
    id: 14,
    categoria: "Burgers",
    nome: "La brasa TUDO Double",
    desc: "Pão australiano, molho verde, bacon, alface, tomate, 2 ovos, 2 burgers de fraldinha 200g, presunto e queijo prato.",
    preco: 26.50,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/7bb79a044960eedc23dcaff4d216837c.png",
    adicionais: true,
    observacoes: true,
  },  {
    id: 15,
    categoria: "Burgers",
    nome: "La brasa TUDO simples",
    desc: "Pão australiano, molho verde, bacon, alface, tomate, ovo, burger de fraldinha 200g, presunto e queijo prato.",
    preco: 20.50,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/8db24ee2dcbeafe879eaaae6d6f76b78.png",
    adicionais: true,
    observacoes: true,
  },  {
    id: 16,
    categoria: "Burgers",
    nome: "La Parma",
    desc: "Pão Com gergelim, molho Gourmet, burger de picanha 200g, cebola roxa, parmesão e bacon.",
    preco: 21.00,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/808a416ab20a3fce1a4d28cc8bd96ef2.png",
    adicionais: true,
    observacoes: true,
  },  {
    id: 17,
    categoria: "Burgers",
    nome: "Picanha Burger",
    desc: "Pão australiano, molho da casa, burger de picanha 200g, catupiry, alho frito, bacon e rúcula.",
    preco: 23.90,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/80a860e7c8cf4c529cb92dc6dca91309.png",
    adicionais: true,
    observacoes: true,
  },
  /* ---------------- COMBOS ---------------- */
  {
    id: 20,
    categoria: "Combos",
    nome: "Combo Chicken",
    desc: "Combo com Burger Chicken (Pão gergelim, molho gourmet, burger de frango, molho 4 queijos e bacon) +Batata + Molho + Refri.Burger Alhopiry + batata ondulada + refrigerante lata.",
    preco: 29.99,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/e9171eb57e9d6ad7b939ac252dc4f575.png",
    adicionais: true,
    observacoes: true,
    destaque: true,
  },
  {
    id: 21,
    categoria: "Combos",
    nome: "Combo Supreme Catupiry",
    desc: "Combo com burger Supreme Catupiry ( pão com gergelim, molho baconese, burger de fraldinha 200g, bacon e catupiry empanado) + batata + molho + refri.",
    preco: 33.99,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/7cd0b2d853de9f0c493caa43c55fde6e.png",
    adicionais: true,
    observacoes: true,
  },
  {
    id: 22,
    categoria: "Combos",
    nome: "Combo La brasa TURBO",
    desc: "Combo com Burger La Brasa TURBO ( pão francês, molho da casa, burger de fraldinha 200g,, queijo prato, bacon, cebola caramelizada, picles, alface e tomate) + batata + molho + refri.",
    preco: 29.99,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/2252cff9c3e53c30806134fc73a22970.png",
    adicionais: true,
    observacoes: true,
  },
  {
    id: 23,
    categoria: "Combos",
    nome: "Combo Double Cheddar",
    desc: "Combo com burger DOUBLE Cheddar ( pão gergelim, molho barbecue, 2 burgers fraldinha 200g, cheddar em dobro, bacon em dobro, picles e cebola caramelizada) + batata, + molho + refri.Combo com Burger La Brasa TURBO ( pão francês, molho da casa, burger de fraldinha 200g,, queijo prato, bacon, cebola caramelizada, picles, alface e tomate) + batata + molho + refri.",
    preco: 39.99,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/0bf541c5b55458637a83aa87779ba315.png",
    adicionais: true,
    observacoes: true,
    destaque: true,
  },  {
    id: 24,
    categoria: "Combos",
    nome: "Combo Supreme Costela",
    desc: "Combo com burger Supreme Costela ( pão brioche, molho verde, burger 100g, bacon, rúcula, catupiry com costela desfiada empanado) + batata + molho + refri.",
    preco: 31.50,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/6456232d6b9b64e539a7aa1c9debc646.png",
    adicionais: true,
    observacoes: true,
  },  {
    id: 25,
    categoria: "Combos",
    nome: "Combo La brasa TURBO DOUBLE",
    desc: "Combo com burger La brasa TURBO DOUBLE (pão francês, molho da casa, 2 burgers fraldinha 200g cada, queijo prato em dobro, bacon em dobro, cebola caramelizada em dobro, picles, alface e tomate) + batata + molho + refri.",
    preco: 35.99,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/4eb64e2ef2edd7c8c8ca49a57d2e372a.png",
    adicionais: true,
    observacoes: true,
  },  {
    id: 26,
    categoria: "Combos",
    nome: "Combo Especial Copa",
    desc: "Burger 100g, queijo prato, bacon, molho verde, alface e tomate, Pão em formato de bola + Batata + refri lata + um pacote de figurinha copa.",
    preco: 27,45,
    imagem: "https://res.cloudinary.com/dlllpozrk/image/upload/v1783311086/imagem_2026-07-06_011101598_zs58wk.png",
    adicionais: true,
    observacoes: true,
  },  {
    id: 27,
    categoria: "Combos",
    nome: "Combo La Parma",
    desc: "Combo com burger La Parma ( pão com gergelim, molho gourmet, burger picanha 200g, cebola roxa, parmesão e bacon) + batata + molho + refri.",
    preco: 29.99,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/f0e96345bbfa8bee6e45ff2a68901577.png",
    adicionais: true,
    observacoes: true,
  },  {
    id: 28,
    categoria: "Combos",
    nome: "Combo Quatro Queijos",
    desc: "Combo com burger Quatro queijos (pão brioche, molho gourmet, burger de picanha 200g, queijo muçarela, catupiry, parmesão e gorgonzola) + batata + molho + refri.Combo com Burger La Brasa TURBO ( pão francês, molho da casa, burger de fraldinha 200g,, queijo prato, bacon, cebola caramelizada, picles, alface e tomate) + batata + molho + refri.",
    preco: 27.99,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/c9559969fe4deb6890212dd677a2348c.png",
    adicionais: true,
    observacoes: true,
  },  {
    id: 29,
    categoria: "Combos",
    nome: "Combo Cheddar",
    desc: "Combo com burger Cheddar ( pão gergelim, molho barbecue, burger fraldinha 200g, cheddar, bacon, picles e cebola caramelizada) + batata + molho + refri.",
    preco: 27.99,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/f408de0a1cc6b8f177a83f23660ad0d1.png",
    adicionais: true,
    observacoes: true,
  },  {
    id: 30,
    categoria: "Combos",
    nome: "Combo Costelão",
    desc: "Combo com burger Costelão (pão francês, molho verde, burger de costela 200g, ovo, queijo prato, bacon, cebola roxa, alface e tomate) + batata + molho + refri.",
    preco: 26.99,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/a073f3a8fc3c4dba0bb368fe5da0dc81.png",
    adicionais: true,
    observacoes: true,
  },  {
    id: 31,
    categoria: "Combos",
    nome: "Combo Texano",
    desc: "Combo com Burger Texano ( pão francês, molho da casa, burger de fraldinha 100g, costela desfiada, catupiry, rúcula, tomate, cebola roxa e bacon) +Batata + Molho + Refri.Combo com burger Costelão (pão francês, molho verde, burger de costela 200g, ovo, queijo prato, bacon, cebola roxa, alface e tomate) + batata + molho + refri.",
    preco: 29.99,
    imagem: "https://static.saipos.com/saipos-estatico/img-items/60944/store_item/c5103da7d024187773f55ed1f653fc03.png",
    adicionais: true,
    observacoes: true,
  },
  /* ---------------- PORÇÕES ---------------- */
  {
    id: 42,
    categoria: "Porções",
    nome: "Batata Grande",
    desc: "Porção de 500g de batata frita crocante.",
    preco: 21.50,
    imagem: "https://res.cloudinary.com/dlllpozrk/image/upload/v1783065109/batata_tbepai.png",
    adicionais: false,
    observacoes: true,
  },
  {
    id: 43,
    categoria: "Porções",
    nome: "Frango a Passarinho",
    desc: "Porção de 700g (400g de batata + 300g de frango a passarinho).",
    preco: 29.90,
    imagem: "https://res.cloudinary.com/dlllpozrk/image/upload/v1783065127/frango_c5cid2.png",
    adicionais: false,
    observacoes: true,
  },
  {
    id: 44,
    categoria: "Porções",
    nome: "Costela BBQ Supreme",
    desc: "Porção de 900g a 1kg de costela bovina macia, finalizada com BBQ, alho crocante e cebolinha fresca. Uma porção bem servida e saborosa.",
    preco: 35.90,
    imagem: "https://res.cloudinary.com/dlllpozrk/image/upload/v1783065383/ChatGPT_Image_3_de_jul._de_2026_04_55_42_si97vp.png",
    adicionais: false,
    observacoes: true,
  },
  {
    id: 45,
    categoria: "Porções",
    nome: "Big Bacon",
    desc: "Porção de 750g (batata frita, bacon crocante e cheddar).",
    preco: 25.90,
    imagem: "https://res.cloudinary.com/dlllpozrk/image/upload/v1783065128/big-bacon_uah6fe.png",
    adicionais: false,
    observacoes: true,
  },
  /* ---------------- BEBIDAS ---------------- */
  {
    id: 51,
    categoria: "Bebidas",
    nome: "Coca-Cola Lata",
    desc: "Refrigerante Coca-Cola, lata 350ml.",
    preco: 7.00,
    imagem: "https://i.pinimg.com/1200x/ae/2d/65/ae2d65d73a98f127fdc0b320b2482c8b.jpg",
    adicionais: false,
    observacoes: false,
  },
  {
    id: 52,
    categoria: "Bebidas",
    nome: "Coca-Cola Lata Zero",
    desc: "Refrigerante Coca-Cola Zero, lata 350ml.",
    preco: 7.00,
    imagem: "https://i.pinimg.com/736x/14/69/c9/1469c92efaab0b5536f9035ab998d2e5.jpg",
    adicionais: false,
    observacoes: false,
  },
  {
    id: 53,
    categoria: "Bebidas",
    nome: "Guaraná Lata",
    desc: "Refrigerante guaraná, lata 350ml.",
    preco: 7.00,
    imagem: "https://i.pinimg.com/736x/f5/7f/cb/f57fcb2cb693db44e97deae59e5e1a44.jpg",
    adicionais: false,
    observacoes: false,
  },
  {
    id: 54,
    categoria: "Bebidas",
    nome: "Sprite Lata",
    desc: "Refrigerante sprite, lata 350ml.Lata 350ml gelada.",
    preco: 7.00,
    imagem: "https://i.pinimg.com/1200x/42/70/aa/4270aae4532dc1e7bd2dacca2843d48b.jpg",
    adicionais: false,
    observacoes: false,
  },
  {
    id: 55,
    categoria: "Bebidas",
    nome: "Pepsi Lata",
    desc: "Refrigerante pepsi, lata 350ml.",
    preco: 7.00,
    imagem: "https://i.pinimg.com/736x/9b/ad/99/9bad993947e87c2c546b8811bba9f9b2.jpg",
    adicionais: false,
    observacoes: false,
  },
  {
    id: 67,
    categoria: "Bebidas",
    nome: "Heineken Garrafa",
    desc: "Cerveja heineken, garrafa 600ml.",
    preco: 9.00,
    imagem: "https://i.pinimg.com/736x/d8/a6/62/d8a6622dd36810741539c28607281567.jpg",
    adicionais: false,
    observacoes: false,
  },
  {
    id: 56,
    categoria: "Bebidas",
    nome: "Budweiser Garrafa",
    desc: "Cerveja budweiser, garrafa 600ml.",
    preco: 9.00,
    imagem: "https://i.pinimg.com/736x/2c/18/39/2c18395dd1e59ff42c0aa6bfd284ae0a.jpg",
    adicionais: false,
    observacoes: false,
  },
  {
    id: 57,
    categoria: "Bebidas",
    nome: "Stella Artois Garrafa",
    desc: "Cerveja stella artois, garrafa 600ml.",
    preco: 10.00,
    imagem: "https://i.pinimg.com/1200x/07/ed/82/07ed82958c59040e38470118f2d313d8.jpg",
    adicionais: false,
    observacoes: false,
  },
  {
    id: 58,
    categoria: "Bebidas",
    nome: "Corona Garrafa",
    desc: "Cerveja corona, garrafa 600ml.",
    preco: 9.00,
    imagem: "https://i.pinimg.com/736x/cf/a0/19/cfa019447778348e7743da13aa86d831.jpg",
    adicionais: false,
    observacoes: false,
  },
  {
    id: 59,
    categoria: "Bebidas",
    nome: "Smirnoff Ice Packshot Garrafa",
    desc: "smirnoff ice packshot, garrafa 275 ml.",
    preco: 10.90,
    imagem: "https://i.pinimg.com/1200x/c3/a0/21/c3a021fbd131944ff39ac70eedeca4a3.jpg",
    adicionais: false,
    observacoes: false,
  },
  {
    id: 60,
    categoria: "Bebidas",
    nome: "Coca-Cola 2L",
    desc: "Refrigerante Coca-Cola, garrafa 2L.",
    preco: 11.90,
    imagem: "https://i.pinimg.com/1200x/3b/a6/6a/3ba66a5f5a22e34372d89cc3f2b1eb74.jpg",
    adicionais: false,
    observacoes: false,
  },
  {
    id: 61,
    categoria: "Bebidas",
    nome: "Coca-Cola 1L",
    desc: "Refrigerante Coca-Cola, garrafa 1L.",
    preco: 7.90,
    imagem: "https://i.pinimg.com/736x/5f/cf/f8/5fcff8ead11de5e970b332c336c7937e.jpg",
    adicionais: false,
    observacoes: false,
  },
  {
    id: 62,
    categoria: "Bebidas",
    nome: "Fanta Laranja Lata 350ml",
    desc: "Refrigerante fanta laranja, lata 350ml.",
    preco: 7.90,
    imagem: "https://i.pinimg.com/736x/e4/30/13/e43013180276de763ce278767f37766c.jpg",
    adicionais: false,
    observacoes: false,
  },
  {
    id: 63,
    categoria: "Bebidas",
    nome: "Fanta Uva Lata 350ml",
    desc: "Refrigerante fanta uva, lata 350ml.",
    preco: 7.90,
    imagem: "https://i.pinimg.com/736x/61/50/52/615052028727816b43b13bbbfa6f0f1f.jpg",
    adicionais: false,
    observacoes: false,
  },
  {
    id: 64,
    categoria: "Bebidas",
    nome: "Garrafa de Água Mineral 500ml",
    desc: "Água mineral, garrafa 500ml.",
    preco: 3.50,
    imagem: "https://drogariacatarinense.vtexassets.com/arquivos/ids/194401-800-1067?v=638149322587470000&width=800&height=1067&aspect=true",
    adicionais: false,
    observacoes: false,
  },
  {
    id: 65,
    categoria: "Bebidas",
    nome: "Garrafa de Água Mineral Com Gás 500ml",
    desc: "Água mineral com gás, garrafa 500ml.",
    preco: 4.50,
    imagem: "https://www.contabilista.com.br/media/catalog/product/cache/e7bd975ee72b2e17c1d729a77564a9f3/0/7/076951A.jpg",
    adicionais: false,
    observacoes: false,
  },
  /* ---------------- BURGER DOCE ---------------- */
  {
    id: 99,
    categoria: "Sobremesas",
    nome: "Milkshake",
    desc: "Milkshake de diversos sabores, servido em copo de 300ml.",
    ingredientes: "Chocolate, morango, baunilha, Ovomaltine, Nutella, Paçoca, Doce de Leite, Oreo.",
    preco: 19.90,
    imagem: "https://res.cloudinary.com/dlllpozrk/image/upload/v1783068372/imagem_2026-07-03_054609373_oewafk.png",
    adicionais: false,
    observacoes: false,
  },
];
